spring:
  sql:
    init:
      enabled: true
  application:
    name: movie-resource
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    "[com.netflix.discovery]": OFF

server:
  port: 8781
