name: Docker Publish

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: movie-resource

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4

      - name: Build with maven
        run: mvn spring-boot:build-image
