name: Docker Publish

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: movie-resource

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4

      - name: Build with maven
        run: mvn spring-boot:build-image
        
  publish:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker
        run: docker push skullgnammer/movie-resource:latest
